version: 2


workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - lint:
          requires:
            - test
      - deploy:
          context: npm_publish
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - develop
                - master

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      
      - persist_to_workspace:
          root: ~/repo
          paths: .
  lint:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint source
          command: yarn ci:lint
      - store_test_results:
          path: ./reports
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - "da:28:93:a2:75:de:ad:b1:24:28:ca:7c:a1:45:4b:38"
      - run:
          name: Publish package
          command: |
            git config --global user.email "circleci@hostmaker.co"
            git config --global user.name "CircleCI"
            git branch -u origin/develop
            npx semantic-release
            
